const pnr = {
    crsId: "1A",
    recordLocator: "",
    creationDate: "yyyyMMdd HHmm",
    creationDateTime: "yyyyMMdd HHmm",
    commencePoint: "",
    nonCommercial: false,
    canceled: false,
    operating: false,
    allotment: false,
    oRespOff: "",
    oPosCnty: "",
    oPosCity: "",
    oPosCrs: "",
    lastArrivalUTC: "yyyyMMdd HHmm",
    extendedLastArrivalUTC: "yyyyMMdd HHmm",
    firstDepartureUTC: "yyyyMMdd HHmm",
    extendedFirstDepartureUTC: "yyyyMMdd HHmm",
    pnrKeys: [],
    respo: null,
    group: null,
    names: [],
    segments: [],
    osis: [],
    remarks: [],
    contacts: [],
    ssrs: [],
    sks: [],
    tickets: [],
    deletedSegmentDescriptors: [],
    eotOriginator: null
}

export default pnr
